# Generated by Django 6.0.1 on 2026-02-22 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Completed', 'Completed'), ('In Progress', 'In Progress'), ('Not Started', 'Not Started')], max_length=20)),
                ('progress', models.IntegerField()),
                ('image', models.ImageField(upload_to='courses/')),
            ],
        ),
    ]
